### ISSUE TITLE
 Result of expression 'element.clone' [undefined] is not a function

### ISSUE THREAD

**Issue by donahchoo** [masylum/jasmine-prototype#3]
I'm fairly new to JS and trying to get Jasmine setup to help me
understand.  I posted this over on the jasmine-js list.  Posting here too...

Anyway,  here's my expectation:

   it("file input should exist", function () {
       loadFixtures('UploadFixture.html', 'another_url');
       var fileInput =
fixturesContainer().getElementsByClassName('fileUploadInput')[0];
       expect(fileInput).toBeDefined();
       expect(fileInput).toExist();
     });

toBeDefined is passing, but toExist is failing...

file input should exist
TypeError: Result of expression 'element.clone' [undefined] is not a
function. in file:///Users/donahchoo/Developer/jasmine/lib/jasmine-1.0.2/jasmine-prototype.js
(line 115)

Any ideas on what I'm doing wrong?

**Comment by masylum** [comment]
if you do a `console.log` of `fileInput`, whats the output?
